#!/bin/sh
xrandr --output eDP --primary --mode 3840x2160 --pos 0x0 --rotate normal --output DisplayPort-0 --mode 3840x1100 --pos 0x2160 --rotate normal --output DP-1-0 --off --output DP-1-1 --off --output HDMI-1-0 --off
