
require 'user.options'
require 'user.plugins'
require 'user.keymaps'
require 'user.colorscheme'
require 'user.lualine'
require 'user.bufferline'
require 'user.treesitter'
require 'user.comment'
require 'user.lsp'
require 'user.cmp'
require 'user.nvim-tree'
require 'user.telescope'
require 'user.illuminate'
require 'user.alpha'
