
require('settings')
require('plugins')
require('colorschemes_config.dracula')
require('keybinds')
require('nvimtree_config')
require('lsp_config.language_servers')
require('lsp_config.cmp_completion')
require('lsp_config.null-ls')
require('lualine_config')
require('barbar_config')
require('treesitter_config')
require('comment_config')
require('autopairs_config')
require('alpha_config')
