
local o = vim.opt

o.backup = false			-- creates a backup file
o.clipboard = 'unnamedplus'	-- allows nvim to access system clipboard
o.cmdheight = 1				-- more space in the command line
o.conceallevel = 0			-- makes `` visible in MD
o.fileencoding = 'utf-8'	-- encoding
o.hlsearch = true			-- highlight all matches
o.ignorecase = true			-- make search case insensitive
o.mouse = 'a'				-- allows for the use of mouse
o.showmode = false			-- toggles mode display (VISUAL, INSERT etc)
o.showtabline = 0			-- always show tabs
o.smartcase = true			-- smart case
o.smartindent = true		-- smart indent
o.splitbelow = true			-- fore all horizontal splits to go below current window
o.splitright = true			-- forea all vertical splits to go right of current window
o.swapfile = false			-- creates a swapfile
o.termguicolors = true		-- set term gui colors
o.timeoutlen = 500			-- time to wait for a mapped sequence to complete (ms)
o.undofile = true			-- enables persistent undo
o.updatetime = 300			-- faster completion (ms, default is 4000)
o.writebackup = false		-- if a file is being edited by another program, it is not allowed to be edited
o.expandtab = false			-- if true, tabs is converted to spaces
o.shiftwidth = 4			-- number of spaces (in tabs if expandtab is false) inserted at indentations
o.tabstop = 4				-- number of spaces (in tabs if expandtab is false) inserted at each tab
o.cursorline = true			-- highlight current line
o.number = true				-- show line numbers
o.relativenumber = true		-- show relative line numbers
o.ruler = false				-- show the line and col number
o.numberwidth = 2			-- set number col width (default 4)
o.signcolumn = 'yes'		-- always show the sign column, otherwise it would shift the text each time
o.wrap = false				-- wrap lines
o.scrolloff = 8				-- minimal number of lines to keep above the cursor
o.sidescrolloff = 8			-- minimal number of colums to keep to the right and left of cursor
o.guifont = 'FiraCode Nerd Font Mono:h8'	-- the font used in graphical nvim applications
o.fillchars.eob = ' '		-- replaces ~ with empty space
o.hidden = true				-- hide buffers instead of deleting when closed (terminal need this to prevent it from opening a new terminal every single time)
